### ISSUE TITLE
Arm64 is now Supported

### ISSUE THREAD

**Issue by lylepratt** [otalk/webrtc-ios#1]
Arm64 is now Supported by WebRTC
https://code.google.com/p/webrtc/issues/detail?id=3898

**Comment by hjon** [comment]
Thanks! I'm working on updating our own stuff to a much newer revision of WebRTC (including arm64). I'd like to confirm that it's all working as expected first, but I plan to update this once I've done that.

**Comment by piemonte** [comment]
@hjon hey there. i've been looking into the webrtc stack and the TLK otalk libraries.

since 64-bit is a new requirement, i rebuilt the webrtc binaries with these instructions:

https://github.com/pristineio/webrtc-build-scripts

i've started doing some updates to the TLK libraries as well. i can send a few pull requests your way if it helps. feel free to email me, if you'd like to talk more or coordinate, wasn't sure how to contact you.

**Comment by piemonte** [comment]
you can see my changes here, https://github.com/piemonte/TLKWebRTC

**Comment by evermeer** [comment]
For anyone interested:
 instead of using
   pod "webrtc-ios"
use:
  pod "libjingle_peerconnection"
Then in TLKWebRTC rename RTCSessionDescriptonDelegate to RTCSessionDescriptionDelegate
And change [peer addStream:self.localMediaStream constraints:[self mediaConstraints]]; into [peer addStream:self.localMediaStream];

**Comment by hjon** [comment]
Given that the modifications we were using have now made their way into the main WebRTC library, I've accepted the changes to the other libraries (TLKWebRTC, etc.) to get up to speed with recent changes and will point others to libjingle_peerconnection in the README.
